theme: jekyll-theme-minimal
title: Simon Wanna
description: Professional swimmer turned engineer.
  On my final year of the Machine Learning master at KTH.

logo: /assets/img/logo.jpg
github:
  is_user_page: true
  is_project_page: false

links:
  linkedin: https://www.linkedin.com/in/simonwanna/

interests:
  - Machine Learning
  - Autonomous Systems
  - Science (AI, sports, human biology, sustainability, behavioural economics)
  - Music (<a href="https://simonwanna.github.io/MusicHabits/" rel="noopener">view my listening habits</a>)
  - Sports (swimming, running, triathlon)